import { Theme } from './types';

export const themes: Record<string, Theme> = {
  dark: {
    id: 'dark',
    name: 'Sombre (par défaut)',
    colors: {
      background: '#0f172a',
      foreground: '#f1f5f9',
      border: '#334155',
      primary: '#3b82f6',
      secondary: '#64748b',
      accent: '#60a5fa',
      sidebar: {
        bg: '#1e293b',
        border: '#334155',
        text: '#f1f5f9',
        active: '#3b82f6',
        hover: '#334155',
      },
      statusBar: {
        bg: '#1e293b',
        border: '#334155',
        text: '#cbd5e1',
      },
      card: {
        bg: '#1e293b',
        border: '#334155',
        text: '#f1f5f9',
      },
      input: {
        bg: '#1e293b',
        border: '#475569',
        text: '#f1f5f9',
        placeholder: '#94a3b8',
        focus: '#3b82f6',
      },
      button: {
        primary: '#3b82f6',
        primaryHover: '#2563eb',
        secondary: '#475569',
        secondaryHover: '#64748b',
      },
      scrollbar: {
        track: '#1e293b',
        thumb: '#475569',
        thumbHover: '#64748b',
      },
      menubar: {
        bg: '#1e293b',
        border: '#334155',
        text: '#f1f5f9',
        hover: '#334155',
        active: '#3b82f6',
        activeText: '#ffffff',
        dropdown: {
          bg: '#1e293b',
          border: '#334155',
          text: '#f1f5f9',
          hover: '#334155',
          separator: '#334155',
        },
        controls: {
          text: '#f1f5f9',
          hover: '#475569',
        },
      },
    },
  },
  orange: {
    id: 'orange',
    name: 'Orange',
    colors: {
      background: '#1c1917',
      foreground: '#faf5f0',
      border: '#57534e',
      primary: '#ea580c',
      secondary: '#a16207',
      accent: '#fb923c',
      sidebar: {
        bg: '#292524',
        border: '#57534e',
        text: '#faf5f0',
        active: '#ea580c',
        hover: '#44403c',
      },
      statusBar: {
        bg: '#292524',
        border: '#57534e',
        text: '#e7c2a0',
      },
      card: {
        bg: '#292524',
        border: '#57534e',
        text: '#faf5f0',
      },
      input: {
        bg: '#292524',
        border: '#78716c',
        text: '#faf5f0',
        placeholder: '#a8a29e',
        focus: '#ea580c',
      },
      button: {
        primary: '#ea580c',
        primaryHover: '#c2410c',
        secondary: '#78716c',
        secondaryHover: '#a8a29e',
      },
      scrollbar: {
        track: '#292524',
        thumb: '#78716c',
        thumbHover: '#a8a29e',
      },
      menubar: {
        bg: '#292524',
        border: '#57534e',
        text: '#faf5f0',
        hover: '#44403c',
        active: '#ea580c',
        activeText: '#ffffff',
        dropdown: {
          bg: '#292524',
          border: '#57534e',
          text: '#faf5f0',
          hover: '#44403c',
          separator: '#57534e',
        },
        controls: {
          text: '#faf5f0',
          hover: '#78716c',
        },
      },
    },
  },
  violet: {
    id: 'violet',
    name: 'Violet',
    colors: {
      background: '#1e1b2e',
      foreground: '#f5f3ff',
      border: '#4c1d95',
      primary: '#8b5cf6',
      secondary: '#7c3aed',
      accent: '#a78bfa',
      sidebar: {
        bg: '#2d1b4e',
        border: '#4c1d95',
        text: '#f5f3ff',
        active: '#8b5cf6',
        hover: '#3b1f6b',
      },
      statusBar: {
        bg: '#2d1b4e',
        border: '#4c1d95',
        text: '#ddd6fe',
      },
      card: {
        bg: '#2d1b4e',
        border: '#4c1d95',
        text: '#f5f3ff',
      },
      input: {
        bg: '#2d1b4e',
        border: '#6d28d9',
        text: '#f5f3ff',
        placeholder: '#a78bfa',
        focus: '#8b5cf6',
      },
      button: {
        primary: '#8b5cf6',
        primaryHover: '#7c3aed',
        secondary: '#6d28d9',
        secondaryHover: '#8b5cf6',
      },
      scrollbar: {
        track: '#2d1b4e',
        thumb: '#6d28d9',
        thumbHover: '#8b5cf6',
      },
      menubar: {
        bg: '#2d1b4e',
        border: '#4c1d95',
        text: '#f5f3ff',
        hover: '#3b1f6b',
        active: '#8b5cf6',
        activeText: '#ffffff',
        dropdown: {
          bg: '#2d1b4e',
          border: '#4c1d95',
          text: '#f5f3ff',
          hover: '#3b1f6b',
          separator: '#4c1d95',
        },
        controls: {
          text: '#f5f3ff',
          hover: '#6d28d9',
        },
      },
    },
  },
  blue: {
    id: 'blue',
    name: 'Bleu',
    colors: {
      background: '#0c1222',
      foreground: '#e0f2fe',
      border: '#1e3a8a',
      primary: '#0ea5e9',
      secondary: '#0284c7',
      accent: '#38bdf8',
      sidebar: {
        bg: '#1e3a5f',
        border: '#1e3a8a',
        text: '#e0f2fe',
        active: '#0ea5e9',
        hover: '#1e40af',
      },
      statusBar: {
        bg: '#1e3a5f',
        border: '#1e3a8a',
        text: '#bae6fd',
      },
      card: {
        bg: '#1e3a5f',
        border: '#1e3a8a',
        text: '#e0f2fe',
      },
      input: {
        bg: '#1e3a5f',
        border: '#3b82f6',
        text: '#e0f2fe',
        placeholder: '#7dd3fc',
        focus: '#0ea5e9',
      },
      button: {
        primary: '#0ea5e9',
        primaryHover: '#0284c7',
        secondary: '#3b82f6',
        secondaryHover: '#60a5fa',
      },
      scrollbar: {
        track: '#1e3a5f',
        thumb: '#3b82f6',
        thumbHover: '#60a5fa',
      },
      menubar: {
        bg: '#1e3a5f',
        border: '#1e3a8a',
        text: '#e0f2fe',
        hover: '#1e40af',
        active: '#0ea5e9',
        activeText: '#ffffff',
        dropdown: {
          bg: '#1e3a5f',
          border: '#1e3a8a',
          text: '#e0f2fe',
          hover: '#1e40af',
          separator: '#1e3a8a',
        },
        controls: {
          text: '#e0f2fe',
          hover: '#3b82f6',
        },
      },
    },
  },
  light: {
    id: 'light',
    name: 'Clair',
    colors: {
      background: '#f8fafc',
      foreground: '#0f172a',
      border: '#cbd5e1',
      primary: '#3b82f6',
      secondary: '#64748b',
      accent: '#60a5fa',
      sidebar: {
        bg: '#ffffff',
        border: '#e2e8f0',
        text: '#0f172a',
        active: '#3b82f6',
        hover: '#f1f5f9',
      },
      statusBar: {
        bg: '#ffffff',
        border: '#e2e8f0',
        text: '#475569',
      },
      card: {
        bg: '#ffffff',
        border: '#e2e8f0',
        text: '#0f172a',
      },
      input: {
        bg: '#ffffff',
        border: '#cbd5e1',
        text: '#0f172a',
        placeholder: '#94a3b8',
        focus: '#3b82f6',
      },
      button: {
        primary: '#3b82f6',
        primaryHover: '#2563eb',
        secondary: '#e2e8f0',
        secondaryHover: '#cbd5e1',
      },
      scrollbar: {
        track: '#f1f5f9',
        thumb: '#cbd5e1',
        thumbHover: '#94a3b8',
      },
      menubar: {
        bg: '#ffffff',
        border: '#e2e8f0',
        text: '#0f172a',
        hover: '#f1f5f9',
        active: '#3b82f6',
        activeText: '#ffffff',
        dropdown: {
          bg: '#ffffff',
          border: '#e2e8f0',
          text: '#0f172a',
          hover: '#f1f5f9',
          separator: '#e2e8f0',
        },
        controls: {
          text: '#0f172a',
          hover: '#e2e8f0',
        },
      },
    },
  },
  emerald: {
    id: 'emerald',
    name: 'Émeraude',
    colors: {
      background: '#0c1a14',
      foreground: '#ecfdf5',
      border: '#065f46',
      primary: '#10b981',
      secondary: '#059669',
      accent: '#34d399',
      sidebar: {
        bg: '#064e3b',
        border: '#065f46',
        text: '#ecfdf5',
        active: '#10b981',
        hover: '#047857',
      },
      statusBar: {
        bg: '#064e3b',
        border: '#065f46',
        text: '#a7f3d0',
      },
      card: {
        bg: '#064e3b',
        border: '#065f46',
        text: '#ecfdf5',
      },
      input: {
        bg: '#064e3b',
        border: '#047857',
        text: '#ecfdf5',
        placeholder: '#6ee7b7',
        focus: '#10b981',
      },
      button: {
        primary: '#10b981',
        primaryHover: '#059669',
        secondary: '#047857',
        secondaryHover: '#10b981',
      },
      scrollbar: {
        track: '#064e3b',
        thumb: '#047857',
        thumbHover: '#10b981',
      },
      menubar: {
        bg: '#064e3b',
        border: '#065f46',
        text: '#ecfdf5',
        hover: '#047857',
        active: '#10b981',
        activeText: '#ffffff',
        dropdown: {
          bg: '#064e3b',
          border: '#065f46',
          text: '#ecfdf5',
          hover: '#047857',
          separator: '#065f46',
        },
        controls: {
          text: '#ecfdf5',
          hover: '#047857',
        },
      },
    },
  },
  rose: {
    id: 'rose',
    name: 'Rose',
    colors: {
      background: '#1f1315',
      foreground: '#fff1f2',
      border: '#881337',
      primary: '#f43f5e',
      secondary: '#e11d48',
      accent: '#fb7185',
      sidebar: {
        bg: '#4c1d24',
        border: '#881337',
        text: '#fff1f2',
        active: '#f43f5e',
        hover: '#5f1f2a',
      },
      statusBar: {
        bg: '#4c1d24',
        border: '#881337',
        text: '#fda4af',
      },
      card: {
        bg: '#4c1d24',
        border: '#881337',
        text: '#fff1f2',
      },
      input: {
        bg: '#4c1d24',
        border: '#9f1239',
        text: '#fff1f2',
        placeholder: '#fda4af',
        focus: '#f43f5e',
      },
      button: {
        primary: '#f43f5e',
        primaryHover: '#e11d48',
        secondary: '#9f1239',
        secondaryHover: '#f43f5e',
      },
      scrollbar: {
        track: '#4c1d24',
        thumb: '#9f1239',
        thumbHover: '#f43f5e',
      },
      menubar: {
        bg: '#4c1d24',
        border: '#881337',
        text: '#fff1f2',
        hover: '#5f1f2a',
        active: '#f43f5e',
        activeText: '#ffffff',
        dropdown: {
          bg: '#4c1d24',
          border: '#881337',
          text: '#fff1f2',
          hover: '#5f1f2a',
          separator: '#881337',
        },
        controls: {
          text: '#fff1f2',
          hover: '#9f1239',
        },
      },
    },
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    colors: {
      background: '#0a0a0f',
      foreground: '#00ff88',
      border: '#ff0080',
      primary: '#00ff88',
      secondary: '#ff0080',
      accent: '#00d9ff',
      sidebar: {
        bg: '#1a0a1a',
        border: '#ff0080',
        text: '#00ff88',
        active: '#00ff88',
        hover: '#2a0a2a',
      },
      statusBar: {
        bg: '#1a0a1a',
        border: '#ff0080',
        text: '#00d9ff',
      },
      card: {
        bg: '#1a0a1a',
        border: '#ff0080',
        text: '#00ff88',
      },
      input: {
        bg: '#1a0a1a',
        border: '#ff0080',
        text: '#00ff88',
        placeholder: '#ff0080',
        focus: '#00ff88',
      },
      button: {
        primary: '#00ff88',
        primaryHover: '#00d9ff',
        secondary: '#ff0080',
        secondaryHover: '#ff3399',
      },
      scrollbar: {
        track: '#1a0a1a',
        thumb: '#ff0080',
        thumbHover: '#00ff88',
      },
      menubar: {
        bg: '#1a0a1a',
        border: '#ff0080',
        text: '#00ff88',
        hover: '#2a0a2a',
        active: '#00ff88',
        activeText: '#0a0a0f',
        dropdown: {
          bg: '#1a0a1a',
          border: '#ff0080',
          text: '#00ff88',
          hover: '#2a0a2a',
          separator: '#ff0080',
        },
        controls: {
          text: '#00ff88',
          hover: '#00d9ff',
        },
      },
    },
  },
  nordic: {
    id: 'nordic',
    name: 'Nordic',
    colors: {
      background: '#2e3440',
      foreground: '#eceff4',
      border: '#4c566a',
      primary: '#88c0d0',
      secondary: '#81a1c1',
      accent: '#5e81ac',
      sidebar: {
        bg: '#3b4252',
        border: '#4c566a',
        text: '#eceff4',
        active: '#88c0d0',
        hover: '#434c5e',
      },
      statusBar: {
        bg: '#3b4252',
        border: '#4c566a',
        text: '#d8dee9',
      },
      card: {
        bg: '#3b4252',
        border: '#4c566a',
        text: '#eceff4',
      },
      input: {
        bg: '#3b4252',
        border: '#5e81ac',
        text: '#eceff4',
        placeholder: '#88c0d0',
        focus: '#88c0d0',
      },
      button: {
        primary: '#88c0d0',
        primaryHover: '#81a1c1',
        secondary: '#5e81ac',
        secondaryHover: '#81a1c1',
      },
      scrollbar: {
        track: '#3b4252',
        thumb: '#5e81ac',
        thumbHover: '#81a1c1',
      },
      menubar: {
        bg: '#3b4252',
        border: '#4c566a',
        text: '#eceff4',
        hover: '#434c5e',
        active: '#88c0d0',
        activeText: '#2e3440',
        dropdown: {
          bg: '#3b4252',
          border: '#4c566a',
          text: '#eceff4',
          hover: '#434c5e',
          separator: '#4c566a',
        },
        controls: {
          text: '#eceff4',
          hover: '#88c0d0',
        },
      },
    },
  },
  amberGold: {
    id: 'amberGold',
    name: 'Amber Gold',
    colors: {
      background: '#1a1612',
      foreground: '#fef3c7',
      border: '#92400e',
      primary: '#f59e0b',
      secondary: '#d97706',
      accent: '#fbbf24',
      sidebar: {
        bg: '#292524',
        border: '#92400e',
        text: '#fef3c7',
        active: '#f59e0b',
        hover: '#3a3530',
      },
      statusBar: {
        bg: '#292524',
        border: '#92400e',
        text: '#fde68a',
      },
      card: {
        bg: '#292524',
        border: '#92400e',
        text: '#fef3c7',
      },
      input: {
        bg: '#292524',
        border: '#b45309',
        text: '#fef3c7',
        placeholder: '#fbbf24',
        focus: '#f59e0b',
      },
      button: {
        primary: '#f59e0b',
        primaryHover: '#fbbf24',
        secondary: '#d97706',
        secondaryHover: '#f59e0b',
      },
      scrollbar: {
        track: '#292524',
        thumb: '#b45309',
        thumbHover: '#f59e0b',
      },
      menubar: {
        bg: '#292524',
        border: '#92400e',
        text: '#fef3c7',
        hover: '#3a3530',
        active: '#f59e0b',
        activeText: '#1a1612',
        dropdown: {
          bg: '#292524',
          border: '#92400e',
          text: '#fef3c7',
          hover: '#3a3530',
          separator: '#92400e',
        },
        controls: {
          text: '#fef3c7',
          hover: '#f59e0b',
        },
      },
    },
  },
  oceanDeep: {
    id: 'oceanDeep',
    name: 'Ocean Deep',
    colors: {
      background: '#0a1929',
      foreground: '#ccd6f6',
      border: '#1e3a5f',
      primary: '#64ffda',
      secondary: '#52d5f2',
      accent: '#8892b0',
      sidebar: {
        bg: '#112240',
        border: '#1e3a5f',
        text: '#ccd6f6',
        active: '#64ffda',
        hover: '#1a2f4f',
      },
      statusBar: {
        bg: '#112240',
        border: '#1e3a5f',
        text: '#8892b0',
      },
      card: {
        bg: '#112240',
        border: '#1e3a5f',
        text: '#ccd6f6',
      },
      input: {
        bg: '#112240',
        border: '#233554',
        text: '#ccd6f6',
        placeholder: '#64ffda',
        focus: '#64ffda',
      },
      button: {
        primary: '#64ffda',
        primaryHover: '#52d5f2',
        secondary: '#233554',
        secondaryHover: '#1e3a5f',
      },
      scrollbar: {
        track: '#112240',
        thumb: '#233554',
        thumbHover: '#64ffda',
      },
      menubar: {
        bg: '#112240',
        border: '#1e3a5f',
        text: '#ccd6f6',
        hover: '#1a2f4f',
        active: '#64ffda',
        activeText: '#0a1929',
        dropdown: {
          bg: '#112240',
          border: '#1e3a5f',
          text: '#ccd6f6',
          hover: '#1a2f4f',
          separator: '#1e3a5f',
        },
        controls: {
          text: '#ccd6f6',
          hover: '#64ffda',
        },
      },
    },
  },
  forest: {
    id: 'forest',
    name: 'Forest',
    colors: {
      background: '#0d1b0f',
      foreground: '#d4edda',
      border: '#1e4620',
      primary: '#28a745',
      secondary: '#20c997',
      accent: '#6cbd7e',
      sidebar: {
        bg: '#1a2e1d',
        border: '#1e4620',
        text: '#d4edda',
        active: '#28a745',
        hover: '#233d27',
      },
      statusBar: {
        bg: '#1a2e1d',
        border: '#1e4620',
        text: '#a8d5ba',
      },
      card: {
        bg: '#1a2e1d',
        border: '#1e4620',
        text: '#d4edda',
      },
      input: {
        bg: '#1a2e1d',
        border: '#2d5a33',
        text: '#d4edda',
        placeholder: '#6cbd7e',
        focus: '#28a745',
      },
      button: {
        primary: '#28a745',
        primaryHover: '#20c997',
        secondary: '#2d5a33',
        secondaryHover: '#28a745',
      },
      scrollbar: {
        track: '#1a2e1d',
        thumb: '#2d5a33',
        thumbHover: '#28a745',
      },
      menubar: {
        bg: '#1a2e1d',
        border: '#1e4620',
        text: '#d4edda',
        hover: '#233d27',
        active: '#28a745',
        activeText: '#0d1b0f',
        dropdown: {
          bg: '#1a2e1d',
          border: '#1e4620',
          text: '#d4edda',
          hover: '#233d27',
          separator: '#1e4620',
        },
        controls: {
          text: '#d4edda',
          hover: '#28a745',
        },
      },
    },
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset',
    colors: {
      background: '#1a0f0a',
      foreground: '#ffe5d9',
      border: '#8b4513',
      primary: '#ff6b35',
      secondary: '#f7931e',
      accent: '#ffa07a',
      sidebar: {
        bg: '#2d1b0f',
        border: '#8b4513',
        text: '#ffe5d9',
        active: '#ff6b35',
        hover: '#3d2b1f',
      },
      statusBar: {
        bg: '#2d1b0f',
        border: '#8b4513',
        text: '#ffcc99',
      },
      card: {
        bg: '#2d1b0f',
        border: '#8b4513',
        text: '#ffe5d9',
      },
      input: {
        bg: '#2d1b0f',
        border: '#a0522d',
        text: '#ffe5d9',
        placeholder: '#ffa07a',
        focus: '#ff6b35',
      },
      button: {
        primary: '#ff6b35',
        primaryHover: '#f7931e',
        secondary: '#a0522d',
        secondaryHover: '#ff6b35',
      },
      scrollbar: {
        track: '#2d1b0f',
        thumb: '#a0522d',
        thumbHover: '#ff6b35',
      },
      menubar: {
        bg: '#2d1b0f',
        border: '#8b4513',
        text: '#ffe5d9',
        hover: '#3d2b1f',
        active: '#ff6b35',
        activeText: '#1a0f0a',
        dropdown: {
          bg: '#2d1b0f',
          border: '#8b4513',
          text: '#ffe5d9',
          hover: '#3d2b1f',
          separator: '#8b4513',
        },
        controls: {
          text: '#ffe5d9',
          hover: '#ff6b35',
        },
      },
    },
  },
  midnightPurple: {
    id: 'midnightPurple',
    name: 'Midnight Purple',
    colors: {
      background: '#1a0d1f',
      foreground: '#e9d5ff',
      border: '#6b21a8',
      primary: '#a855f7',
      secondary: '#9333ea',
      accent: '#c084fc',
      sidebar: {
        bg: '#2d1b3d',
        border: '#6b21a8',
        text: '#e9d5ff',
        active: '#a855f7',
        hover: '#3d2b4d',
      },
      statusBar: {
        bg: '#2d1b3d',
        border: '#6b21a8',
        text: '#d8b4fe',
      },
      card: {
        bg: '#2d1b3d',
        border: '#6b21a8',
        text: '#e9d5ff',
      },
      input: {
        bg: '#2d1b3d',
        border: '#7c3aed',
        text: '#e9d5ff',
        placeholder: '#c084fc',
        focus: '#a855f7',
      },
      button: {
        primary: '#a855f7',
        primaryHover: '#c084fc',
        secondary: '#7c3aed',
        secondaryHover: '#a855f7',
      },
      scrollbar: {
        track: '#2d1b3d',
        thumb: '#7c3aed',
        thumbHover: '#a855f7',
      },
      menubar: {
        bg: '#2d1b3d',
        border: '#6b21a8',
        text: '#e9d5ff',
        hover: '#3d2b4d',
        active: '#a855f7',
        activeText: '#1a0d1f',
        dropdown: {
          bg: '#2d1b3d',
          border: '#6b21a8',
          text: '#e9d5ff',
          hover: '#3d2b4d',
          separator: '#6b21a8',
        },
        controls: {
          text: '#e9d5ff',
          hover: '#a855f7',
        },
      },
    },
  },
  matrix: {
    id: 'matrix',
    name: 'Matrix',
    colors: {
      background: '#0a0a0a',
      foreground: '#00ff41',
      border: '#003b00',
      primary: '#00ff41',
      secondary: '#00cc33',
      accent: '#39ff14',
      sidebar: {
        bg: '#0d1a0d',
        border: '#003b00',
        text: '#00ff41',
        active: '#00ff41',
        hover: '#1a2a1a',
      },
      statusBar: {
        bg: '#0d1a0d',
        border: '#003b00',
        text: '#39ff14',
      },
      card: {
        bg: '#0d1a0d',
        border: '#003b00',
        text: '#00ff41',
      },
      input: {
        bg: '#0d1a0d',
        border: '#006600',
        text: '#00ff41',
        placeholder: '#00cc33',
        focus: '#00ff41',
      },
      button: {
        primary: '#00ff41',
        primaryHover: '#39ff14',
        secondary: '#006600',
        secondaryHover: '#00cc33',
      },
      scrollbar: {
        track: '#0d1a0d',
        thumb: '#006600',
        thumbHover: '#00ff41',
      },
      menubar: {
        bg: '#0d1a0d',
        border: '#003b00',
        text: '#00ff41',
        hover: '#1a2a1a',
        active: '#00ff41',
        activeText: '#0a0a0a',
        dropdown: {
          bg: '#0d1a0d',
          border: '#003b00',
          text: '#00ff41',
          hover: '#1a2a1a',
          separator: '#003b00',
        },
        controls: {
          text: '#00ff41',
          hover: '#39ff14',
        },
      },
    },
  },
  royal: {
    id: 'royal',
    name: 'Royal',
    colors: {
      background: '#0f0c1a',
      foreground: '#e8e2f4',
      border: '#4a3c6b',
      primary: '#8b5cf6',
      secondary: '#7c3aed',
      accent: '#a78bfa',
      sidebar: {
        bg: '#1e1a2e',
        border: '#4a3c6b',
        text: '#e8e2f4',
        active: '#8b5cf6',
        hover: '#2d2542',
      },
      statusBar: {
        bg: '#1e1a2e',
        border: '#4a3c6b',
        text: '#c4b5fd',
      },
      card: {
        bg: '#1e1a2e',
        border: '#4a3c6b',
        text: '#e8e2f4',
      },
      input: {
        bg: '#1e1a2e',
        border: '#6d5a8f',
        text: '#e8e2f4',
        placeholder: '#a78bfa',
        focus: '#8b5cf6',
      },
      button: {
        primary: '#8b5cf6',
        primaryHover: '#a78bfa',
        secondary: '#6d5a8f',
        secondaryHover: '#8b5cf6',
      },
      scrollbar: {
        track: '#1e1a2e',
        thumb: '#6d5a8f',
        thumbHover: '#8b5cf6',
      },
      menubar: {
        bg: '#1e1a2e',
        border: '#4a3c6b',
        text: '#e8e2f4',
        hover: '#2d2542',
        active: '#8b5cf6',
        activeText: '#0f0c1a',
        dropdown: {
          bg: '#1e1a2e',
          border: '#4a3c6b',
          text: '#e8e2f4',
          hover: '#2d2542',
          separator: '#4a3c6b',
        },
        controls: {
          text: '#e8e2f4',
          hover: '#8b5cf6',
        },
      },
    },
  },
  cherryBlossom: {
    id: 'cherryBlossom',
    name: 'Cherry Blossom',
    colors: {
      background: '#1f0f1a',
      foreground: '#ffeef5',
      border: '#8b4a6b',
      primary: '#ff69b4',
      secondary: '#ff1493',
      accent: '#ffb6c1',
      sidebar: {
        bg: '#2d1a25',
        border: '#8b4a6b',
        text: '#ffeef5',
        active: '#ff69b4',
        hover: '#3d2a35',
      },
      statusBar: {
        bg: '#2d1a25',
        border: '#8b4a6b',
        text: '#ffb6c1',
      },
      card: {
        bg: '#2d1a25',
        border: '#8b4a6b',
        text: '#ffeef5',
      },
      input: {
        bg: '#2d1a25',
        border: '#a05a7a',
        text: '#ffeef5',
        placeholder: '#ffb6c1',
        focus: '#ff69b4',
      },
      button: {
        primary: '#ff69b4',
        primaryHover: '#ff1493',
        secondary: '#a05a7a',
        secondaryHover: '#ff69b4',
      },
      scrollbar: {
        track: '#2d1a25',
        thumb: '#a05a7a',
        thumbHover: '#ff69b4',
      },
      menubar: {
        bg: '#2d1a25',
        border: '#8b4a6b',
        text: '#ffeef5',
        hover: '#3d2a35',
        active: '#ff69b4',
        activeText: '#1f0f1a',
        dropdown: {
          bg: '#2d1a25',
          border: '#8b4a6b',
          text: '#ffeef5',
          hover: '#3d2a35',
          separator: '#8b4a6b',
        },
        controls: {
          text: '#ffeef5',
          hover: '#ff69b4',
        },
      },
    },
  },
  neonBlue: {
    id: 'neonBlue',
    name: 'Neon Blue',
    colors: {
      background: '#0a0e27',
      foreground: '#b3e5fc',
      border: '#0277bd',
      primary: '#00bcd4',
      secondary: '#0097a7',
      accent: '#4dd0e1',
      sidebar: {
        bg: '#1a1f3a',
        border: '#0277bd',
        text: '#b3e5fc',
        active: '#00bcd4',
        hover: '#2a2f4a',
      },
      statusBar: {
        bg: '#1a1f3a',
        border: '#0277bd',
        text: '#81d4fa',
      },
      card: {
        bg: '#1a1f3a',
        border: '#0277bd',
        text: '#b3e5fc',
      },
      input: {
        bg: '#1a1f3a',
        border: '#0288d1',
        text: '#b3e5fc',
        placeholder: '#4dd0e1',
        focus: '#00bcd4',
      },
      button: {
        primary: '#00bcd4',
        primaryHover: '#4dd0e1',
        secondary: '#0288d1',
        secondaryHover: '#00bcd4',
      },
      scrollbar: {
        track: '#1a1f3a',
        thumb: '#0288d1',
        thumbHover: '#00bcd4',
      },
      menubar: {
        bg: '#1a1f3a',
        border: '#0277bd',
        text: '#b3e5fc',
        hover: '#2a2f4a',
        active: '#00bcd4',
        activeText: '#0a0e27',
        dropdown: {
          bg: '#1a1f3a',
          border: '#0277bd',
          text: '#b3e5fc',
          hover: '#2a2f4a',
          separator: '#0277bd',
        },
        controls: {
          text: '#b3e5fc',
          hover: '#00bcd4',
        },
      },
    },
  },
  crimson: {
    id: 'crimson',
    name: 'Crimson',
    colors: {
      background: '#1a0a0a',
      foreground: '#ffe0e0',
      border: '#8b0000',
      primary: '#dc143c',
      secondary: '#b22222',
      accent: '#ff6b6b',
      sidebar: {
        bg: '#2d1a1a',
        border: '#8b0000',
        text: '#ffe0e0',
        active: '#dc143c',
        hover: '#3d2a2a',
      },
      statusBar: {
        bg: '#2d1a1a',
        border: '#8b0000',
        text: '#ff9999',
      },
      card: {
        bg: '#2d1a1a',
        border: '#8b0000',
        text: '#ffe0e0',
      },
      input: {
        bg: '#2d1a1a',
        border: '#a00000',
        text: '#ffe0e0',
        placeholder: '#ff6b6b',
        focus: '#dc143c',
      },
      button: {
        primary: '#dc143c',
        primaryHover: '#ff6b6b',
        secondary: '#a00000',
        secondaryHover: '#dc143c',
      },
      scrollbar: {
        track: '#2d1a1a',
        thumb: '#a00000',
        thumbHover: '#dc143c',
      },
      menubar: {
        bg: '#2d1a1a',
        border: '#8b0000',
        text: '#ffe0e0',
        hover: '#3d2a2a',
        active: '#dc143c',
        activeText: '#1a0a0a',
        dropdown: {
          bg: '#2d1a1a',
          border: '#8b0000',
          text: '#ffe0e0',
          hover: '#3d2a2a',
          separator: '#8b0000',
        },
        controls: {
          text: '#ffe0e0',
          hover: '#dc143c',
        },
      },
    },
  },
  aurora: {
    id: 'aurora',
    name: 'Aurora',
    colors: {
      background: '#0a0f1a',
      foreground: '#e0f2fe',
      border: '#1e3a8a',
      primary: '#06b6d4',
      secondary: '#0891b2',
      accent: '#22d3ee',
      sidebar: {
        bg: '#1a1f2e',
        border: '#1e3a8a',
        text: '#e0f2fe',
        active: '#06b6d4',
        hover: '#2a2f3e',
      },
      statusBar: {
        bg: '#1a1f2e',
        border: '#1e3a8a',
        text: '#a5f3fc',
      },
      card: {
        bg: '#1a1f2e',
        border: '#1e3a8a',
        text: '#e0f2fe',
      },
      input: {
        bg: '#1a1f2e',
        border: '#2563eb',
        text: '#e0f2fe',
        placeholder: '#22d3ee',
        focus: '#06b6d4',
      },
      button: {
        primary: '#06b6d4',
        primaryHover: '#22d3ee',
        secondary: '#2563eb',
        secondaryHover: '#06b6d4',
      },
      scrollbar: {
        track: '#1a1f2e',
        thumb: '#2563eb',
        thumbHover: '#06b6d4',
      },
      menubar: {
        bg: '#1a1f2e',
        border: '#1e3a8a',
        text: '#e0f2fe',
        hover: '#2a2f3e',
        active: '#06b6d4',
        activeText: '#0a0f1a',
        dropdown: {
          bg: '#1a1f2e',
          border: '#1e3a8a',
          text: '#e0f2fe',
          hover: '#2a2f3e',
          separator: '#1e3a8a',
        },
        controls: {
          text: '#e0f2fe',
          hover: '#06b6d4',
        },
      },
    },
  },
  emeraldNight: {
    id: 'emeraldNight',
    name: 'Emerald Night',
    colors: {
      background: '#0a1a0f',
      foreground: '#d1fae5',
      border: '#065f46',
      primary: '#10b981',
      secondary: '#059669',
      accent: '#34d399',
      sidebar: {
        bg: '#1a2a1f',
        border: '#065f46',
        text: '#d1fae5',
        active: '#10b981',
        hover: '#2a3a2f',
      },
      statusBar: {
        bg: '#1a2a1f',
        border: '#065f46',
        text: '#6ee7b7',
      },
      card: {
        bg: '#1a2a1f',
        border: '#065f46',
        text: '#d1fae5',
      },
      input: {
        bg: '#1a2a1f',
        border: '#047857',
        text: '#d1fae5',
        placeholder: '#34d399',
        focus: '#10b981',
      },
      button: {
        primary: '#10b981',
        primaryHover: '#34d399',
        secondary: '#047857',
        secondaryHover: '#10b981',
      },
      scrollbar: {
        track: '#1a2a1f',
        thumb: '#047857',
        thumbHover: '#10b981',
      },
      menubar: {
        bg: '#1a2a1f',
        border: '#065f46',
        text: '#d1fae5',
        hover: '#2a3a2f',
        active: '#10b981',
        activeText: '#0a1a0f',
        dropdown: {
          bg: '#1a2a1f',
          border: '#065f46',
          text: '#d1fae5',
          hover: '#2a3a2f',
          separator: '#065f46',
        },
        controls: {
          text: '#d1fae5',
          hover: '#10b981',
        },
      },
    },
  },
  cosmic: {
    id: 'cosmic',
    name: 'Cosmic',
    colors: {
      background: '#0a0a1a',
      foreground: '#e0d5ff',
      border: '#4a3c6b',
      primary: '#9333ea',
      secondary: '#7c3aed',
      accent: '#a78bfa',
      sidebar: {
        bg: '#1a1a2e',
        border: '#4a3c6b',
        text: '#e0d5ff',
        active: '#9333ea',
        hover: '#2a2a3e',
      },
      statusBar: {
        bg: '#1a1a2e',
        border: '#4a3c6b',
        text: '#c4b5fd',
      },
      card: {
        bg: '#1a1a2e',
        border: '#4a3c6b',
        text: '#e0d5ff',
      },
      input: {
        bg: '#1a1a2e',
        border: '#6d5a8f',
        text: '#e0d5ff',
        placeholder: '#a78bfa',
        focus: '#9333ea',
      },
      button: {
        primary: '#9333ea',
        primaryHover: '#a78bfa',
        secondary: '#6d5a8f',
        secondaryHover: '#9333ea',
      },
      scrollbar: {
        track: '#1a1a2e',
        thumb: '#6d5a8f',
        thumbHover: '#9333ea',
      },
      menubar: {
        bg: '#1a1a2e',
        border: '#4a3c6b',
        text: '#e0d5ff',
        hover: '#2a2a3e',
        active: '#9333ea',
        activeText: '#0a0a1a',
        dropdown: {
          bg: '#1a1a2e',
          border: '#4a3c6b',
          text: '#e0d5ff',
          hover: '#2a2a3e',
          separator: '#4a3c6b',
        },
        controls: {
          text: '#e0d5ff',
          hover: '#9333ea',
        },
      },
    },
  },
};

export const defaultTheme = themes.dark;

const CUSTOM_THEME_STORAGE = 'fic_inspector_custom_theme';

export const getTheme = (themeId: string): Theme => {
  // Si c'est le thème personnalisé, le charger depuis localStorage
  if (themeId === 'custom') {
    try {
      const customThemeStored = localStorage.getItem(CUSTOM_THEME_STORAGE);
      if (customThemeStored) {
        const parsed = JSON.parse(customThemeStored);
        const customTheme: Theme = {
          id: 'custom',
          name: 'Personnalisé',
          colors: parsed as Theme['colors'],
        };
        // Ajouter temporairement aux thèmes disponibles
        (themes as any).custom = customTheme;
        return customTheme;
      }
    } catch (e) {
      console.error('Erreur lors du chargement du thème personnalisé:', e);
    }
  }
  
  return themes[themeId] || defaultTheme;
};

